name: Regression test for redis-adequate-rate-limiter

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Run tests
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
          bundle exec rspec spec/redis/adequate_rate_limiter_spec.rb
